### ISSUE TITLE
Please make it available for Windows and Mac OS

### ISSUE THREAD

**Issue by lucaspestana** [ClassicOS-Themes/ClassicOS-2000-Icons#4]
First off, congratulations on these icons, they look really great!

**My suggestion is, could you please make them available as ready to use as .ICO, .PNG (and maybe .ICNS) files?**
I am not a Linux user, and I failed to properly convert the files available to a format I could use (I'm currently on the latest build of Windows 10, version 21H2).

I really like your icons because they're rescalable and significantly more high-resolution than any other Windows 2000-inspired icons available elsewhere or from the original .DLL files.

Thank you so much!

**Comment by ClassicOS-Themes** [comment]
I have added to the build script so that now one can use `make png` or `make ico` to produce png / ico versions.

You'll still (most likely) need Linux or a unix-like platform to generate the files, but it should be doable in WSL if you're on Windows - just ensure that imagemagick and inkscape are installed in your WSL environment.

I don't use Windows so I can't say how well the converted icons will work.
